// Code generated by MockGen. DO NOT EDIT.
// Source: paymentfc/cmd/payment/service (interfaces: XenditService)

package service

import (
	context "context"
	models "paymentfc/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockXenditService is a mock of XenditService interface.
type MockXenditService struct {
	ctrl     *gomock.Controller
	recorder *MockXenditServiceMockRecorder
}

// MockXenditServiceMockRecorder is the mock recorder for MockXenditService.
type MockXenditServiceMockRecorder struct {
	mock *MockXenditService
}

// NewMockXenditService creates a new mock instance.
func NewMockXenditService(ctrl *gomock.Controller) *MockXenditService {
	mock := &MockXenditService{ctrl: ctrl}
	mock.recorder = &MockXenditServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXenditService) EXPECT() *MockXenditServiceMockRecorder {
	return m.recorder
}

// CheckInvoiceStatus mocks base method.
func (m *MockXenditService) CheckInvoiceStatus(ctx context.Context, externalID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInvoiceStatus", ctx, externalID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInvoiceStatus indicates an expected call of CheckInvoiceStatus.
func (mr *MockXenditServiceMockRecorder) CheckInvoiceStatus(ctx, externalID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInvoiceStatus", reflect.TypeOf((*MockXenditService)(nil).CheckInvoiceStatus), ctx, externalID)
}

// CreateInvoice mocks base method.
func (m *MockXenditService) CreateInvoice(ctx context.Context, param models.OrderCreatedEvent) (*models.XenditInvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", ctx, param)
	ret0, _ := ret[0].(*models.XenditInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockXenditServiceMockRecorder) CreateInvoice(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockXenditService)(nil).CreateInvoice), ctx, param)
}

// CreateInvoiceFromPaymentRequest mocks base method.
func (m *MockXenditService) CreateInvoiceFromPaymentRequest(ctx context.Context, pr *models.PaymentRequest) (*models.XenditInvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoiceFromPaymentRequest", ctx, pr)
	ret0, _ := ret[0].(*models.XenditInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoiceFromPaymentRequest indicates an expected call of CreateInvoiceFromPaymentRequest.
func (mr *MockXenditServiceMockRecorder) CreateInvoiceFromPaymentRequest(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoiceFromPaymentRequest", reflect.TypeOf((*MockXenditService)(nil).CreateInvoiceFromPaymentRequest), ctx, pr)
}
