// Code generated by MockGen. DO NOT EDIT.
// Source: paymentfc/cmd/payment/service (interfaces: PaymentService)

package service

import (
	context "context"
	models "paymentfc/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentService is a mock of PaymentService interface.
type MockPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceMockRecorder
}

// MockPaymentServiceMockRecorder is the mock recorder for MockPaymentService.
type MockPaymentServiceMockRecorder struct {
	mock *MockPaymentService
}

// NewMockPaymentService creates a new mock instance.
func NewMockPaymentService(ctrl *gomock.Controller) *MockPaymentService {
	mock := &MockPaymentService{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentService) EXPECT() *MockPaymentServiceMockRecorder {
	return m.recorder
}

// GetAmountByOrderID mocks base method.
func (m *MockPaymentService) GetAmountByOrderID(ctx context.Context, orderID int64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAmountByOrderID", ctx, orderID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAmountByOrderID indicates an expected call of GetAmountByOrderID.
func (mr *MockPaymentServiceMockRecorder) GetAmountByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAmountByOrderID", reflect.TypeOf((*MockPaymentService)(nil).GetAmountByOrderID), ctx, orderID)
}

// GetPaymentByOrderID mocks base method.
func (m *MockPaymentService) GetPaymentByOrderID(ctx context.Context, orderID int64) (*models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByOrderID indicates an expected call of GetPaymentByOrderID.
func (mr *MockPaymentServiceMockRecorder) GetPaymentByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByOrderID", reflect.TypeOf((*MockPaymentService)(nil).GetPaymentByOrderID), ctx, orderID)
}

// IsAlreadyPaid mocks base method.
func (m *MockPaymentService) IsAlreadyPaid(ctx context.Context, orderID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAlreadyPaid", ctx, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAlreadyPaid indicates an expected call of IsAlreadyPaid.
func (mr *MockPaymentServiceMockRecorder) IsAlreadyPaid(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAlreadyPaid", reflect.TypeOf((*MockPaymentService)(nil).IsAlreadyPaid), ctx, orderID)
}

// ProcessPaymentSuccess mocks base method.
func (m *MockPaymentService) ProcessPaymentSuccess(ctx context.Context, orderID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPaymentSuccess", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPaymentSuccess indicates an expected call of ProcessPaymentSuccess.
func (mr *MockPaymentServiceMockRecorder) ProcessPaymentSuccess(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPaymentSuccess", reflect.TypeOf((*MockPaymentService)(nil).ProcessPaymentSuccess), ctx, orderID)
}

// ProcessPaymentFailed mocks base method.
func (m *MockPaymentService) ProcessPaymentFailed(ctx context.Context, orderID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPaymentFailed", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPaymentFailed indicates an expected call of ProcessPaymentFailed.
func (mr *MockPaymentServiceMockRecorder) ProcessPaymentFailed(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPaymentFailed", reflect.TypeOf((*MockPaymentService)(nil).ProcessPaymentFailed), ctx, orderID)
}

// SaveFailedPublishEvent mocks base method.
func (m *MockPaymentService) SaveFailedPublishEvent(ctx context.Context, param *models.FailedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFailedPublishEvent", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFailedPublishEvent indicates an expected call of SaveFailedPublishEvent.
func (mr *MockPaymentServiceMockRecorder) SaveFailedPublishEvent(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFailedPublishEvent", reflect.TypeOf((*MockPaymentService)(nil).SaveFailedPublishEvent), ctx, param)
}

// SavePaymentAnomaly mocks base method.
func (m *MockPaymentService) SavePaymentAnomaly(ctx context.Context, param *models.PaymentAnomaly) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePaymentAnomaly", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePaymentAnomaly indicates an expected call of SavePaymentAnomaly.
func (mr *MockPaymentServiceMockRecorder) SavePaymentAnomaly(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePaymentAnomaly", reflect.TypeOf((*MockPaymentService)(nil).SavePaymentAnomaly), ctx, param)
}

// SavePaymentRequestFromEvent mocks base method.
func (m *MockPaymentService) SavePaymentRequestFromEvent(ctx context.Context, event models.OrderCreatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePaymentRequestFromEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePaymentRequestFromEvent indicates an expected call of SavePaymentRequestFromEvent.
func (mr *MockPaymentServiceMockRecorder) SavePaymentRequestFromEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePaymentRequestFromEvent", reflect.TypeOf((*MockPaymentService)(nil).SavePaymentRequestFromEvent), ctx, event)
}

// GetFailedPaymentList mocks base method.
func (m *MockPaymentService) GetFailedPaymentList(ctx context.Context) ([]models.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailedPaymentList", ctx)
	ret0, _ := ret[0].([]models.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFailedPaymentList indicates an expected call of GetFailedPaymentList.
func (mr *MockPaymentServiceMockRecorder) GetFailedPaymentList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailedPaymentList", reflect.TypeOf((*MockPaymentService)(nil).GetFailedPaymentList), ctx)
}

// ListAuditLogs mocks base method.
func (m *MockPaymentService) ListAuditLogs(ctx context.Context, filter models.AuditLogFilter) (models.AuditLogPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditLogs", ctx, filter)
	ret0, _ := ret[0].(models.AuditLogPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditLogs indicates an expected call of ListAuditLogs.
func (mr *MockPaymentServiceMockRecorder) ListAuditLogs(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditLogs", reflect.TypeOf((*MockPaymentService)(nil).ListAuditLogs), ctx, filter)
}

// GetAuditDailyReport mocks base method.
func (m *MockPaymentService) GetAuditDailyReport(ctx context.Context, from, to time.Time) ([]models.AuditDailyReportItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditDailyReport", ctx, from, to)
	ret0, _ := ret[0].([]models.AuditDailyReportItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditDailyReport indicates an expected call of GetAuditDailyReport.
func (mr *MockPaymentServiceMockRecorder) GetAuditDailyReport(ctx, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditDailyReport", reflect.TypeOf((*MockPaymentService)(nil).GetAuditDailyReport), ctx, from, to)
}

// WatchAuditInsertStream mocks base method.
func (m *MockPaymentService) WatchAuditInsertStream(ctx context.Context, out chan<- models.PaymentAuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchAuditInsertStream", ctx, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// WatchAuditInsertStream indicates an expected call of WatchAuditInsertStream.
func (mr *MockPaymentServiceMockRecorder) WatchAuditInsertStream(ctx, out interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchAuditInsertStream", reflect.TypeOf((*MockPaymentService)(nil).WatchAuditInsertStream), ctx, out)
}
