// Code generated by MockGen. DO NOT EDIT.
// Source: paymentfc/grpc (interfaces: UserClientInterface)

package mocks

import (
	context "context"
	pb "paymentfc/pb/proto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserClientInterface is a mock of UserClientInterface.
type MockUserClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserClientInterfaceMockRecorder
}

// MockUserClientInterfaceMockRecorder is the mock recorder for MockUserClientInterface.
type MockUserClientInterfaceMockRecorder struct {
	mock *MockUserClientInterface
}

// NewMockUserClientInterface creates a new mock instance.
func NewMockUserClientInterface(ctrl *gomock.Controller) *MockUserClientInterface {
	mock := &MockUserClientInterface{ctrl: ctrl}
	mock.recorder = &MockUserClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserClientInterface) EXPECT() *MockUserClientInterfaceMockRecorder {
	return m.recorder
}

// GetUserInfoByUserId mocks base method.
func (m *MockUserClientInterface) GetUserInfoByUserId(ctx context.Context, userId int64) (*pb.GetUserInfoByUserIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfoByUserId", ctx, userId)
	ret0, _ := ret[0].(*pb.GetUserInfoByUserIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfoByUserId indicates an expected call of GetUserInfoByUserId.
func (mr *MockUserClientInterfaceMockRecorder) GetUserInfoByUserId(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfoByUserId", reflect.TypeOf((*MockUserClientInterface)(nil).GetUserInfoByUserId), ctx, userId)
}

// ValidateToken mocks base method.
func (m *MockUserClientInterface) ValidateToken(ctx context.Context, token string) (*pb.ValidateTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(*pb.ValidateTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockUserClientInterfaceMockRecorder) ValidateToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockUserClientInterface)(nil).ValidateToken), ctx, token)
}

// Close mocks base method.
func (m *MockUserClientInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockUserClientInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockUserClientInterface)(nil).Close))
}
