// Code generated by MockGen. DO NOT EDIT.
// Source: paymentfc/cmd/payment/repository (interfaces: PaymentDatabase,XenditClient,PaymentEventPublisher,AuditLogRepository)

package mocks

import (
	context "context"
	models "paymentfc/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentDatabase is a mock of PaymentDatabase interface.
type MockPaymentDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentDatabaseMockRecorder
}

// MockPaymentDatabaseMockRecorder is the mock recorder for MockPaymentDatabase.
type MockPaymentDatabaseMockRecorder struct {
	mock *MockPaymentDatabase
}

// NewMockPaymentDatabase creates a new mock instance.
func NewMockPaymentDatabase(ctrl *gomock.Controller) *MockPaymentDatabase {
	mock := &MockPaymentDatabase{ctrl: ctrl}
	mock.recorder = &MockPaymentDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentDatabase) EXPECT() *MockPaymentDatabaseMockRecorder {
	return m.recorder
}

// GetExpiredPendingPayments mocks base method.
func (m *MockPaymentDatabase) GetExpiredPendingPayments(ctx context.Context) ([]models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiredPendingPayments", ctx)
	ret0, _ := ret[0].([]models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiredPendingPayments indicates an expected call of GetExpiredPendingPayments.
func (mr *MockPaymentDatabaseMockRecorder) GetExpiredPendingPayments(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiredPendingPayments", reflect.TypeOf((*MockPaymentDatabase)(nil).GetExpiredPendingPayments), ctx)
}

// GetFailedPaymentRequests mocks base method.
func (m *MockPaymentDatabase) GetFailedPaymentRequests(ctx context.Context) ([]models.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailedPaymentRequests", ctx)
	ret0, _ := ret[0].([]models.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFailedPaymentRequests indicates an expected call of GetFailedPaymentRequests.
func (mr *MockPaymentDatabaseMockRecorder) GetFailedPaymentRequests(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailedPaymentRequests", reflect.TypeOf((*MockPaymentDatabase)(nil).GetFailedPaymentRequests), ctx)
}

// GetFailedPaymentList mocks base method.
func (m *MockPaymentDatabase) GetFailedPaymentList(ctx context.Context) ([]models.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailedPaymentList", ctx)
	ret0, _ := ret[0].([]models.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFailedPaymentList indicates an expected call of GetFailedPaymentList.
func (mr *MockPaymentDatabaseMockRecorder) GetFailedPaymentList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailedPaymentList", reflect.TypeOf((*MockPaymentDatabase)(nil).GetFailedPaymentList), ctx)
}

// GetPaymentByOrderID mocks base method.
func (m *MockPaymentDatabase) GetPaymentByOrderID(ctx context.Context, orderID int64) (*models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByOrderID indicates an expected call of GetPaymentByOrderID.
func (mr *MockPaymentDatabaseMockRecorder) GetPaymentByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByOrderID", reflect.TypeOf((*MockPaymentDatabase)(nil).GetPaymentByOrderID), ctx, orderID)
}

// GetPendingInvoices mocks base method.
func (m *MockPaymentDatabase) GetPendingInvoices(ctx context.Context) ([]models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingInvoices", ctx)
	ret0, _ := ret[0].([]models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingInvoices indicates an expected call of GetPendingInvoices.
func (mr *MockPaymentDatabaseMockRecorder) GetPendingInvoices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingInvoices", reflect.TypeOf((*MockPaymentDatabase)(nil).GetPendingInvoices), ctx)
}

// GetPendingPaymentRequests mocks base method.
func (m *MockPaymentDatabase) GetPendingPaymentRequests(ctx context.Context) ([]models.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingPaymentRequests", ctx)
	ret0, _ := ret[0].([]models.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingPaymentRequests indicates an expected call of GetPendingPaymentRequests.
func (mr *MockPaymentDatabaseMockRecorder) GetPendingPaymentRequests(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingPaymentRequests", reflect.TypeOf((*MockPaymentDatabase)(nil).GetPendingPaymentRequests), ctx)
}

// IsAlreadyPaid mocks base method.
func (m *MockPaymentDatabase) IsAlreadyPaid(ctx context.Context, orderID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAlreadyPaid", ctx, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAlreadyPaid indicates an expected call of IsAlreadyPaid.
func (mr *MockPaymentDatabaseMockRecorder) IsAlreadyPaid(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAlreadyPaid", reflect.TypeOf((*MockPaymentDatabase)(nil).IsAlreadyPaid), ctx, orderID)
}

// MarkExpired mocks base method.
func (m *MockPaymentDatabase) MarkExpired(ctx context.Context, paymentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkExpired", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkExpired indicates an expected call of MarkExpired.
func (mr *MockPaymentDatabaseMockRecorder) MarkExpired(ctx, paymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkExpired", reflect.TypeOf((*MockPaymentDatabase)(nil).MarkExpired), ctx, paymentID)
}

// MarkPaid mocks base method.
func (m *MockPaymentDatabase) MarkPaid(orderID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPaid", orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPaid indicates an expected call of MarkPaid.
func (mr *MockPaymentDatabaseMockRecorder) MarkPaid(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaid", reflect.TypeOf((*MockPaymentDatabase)(nil).MarkPaid), orderID)
}

// MarkFailed mocks base method.
func (m *MockPaymentDatabase) MarkFailed(orderID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockPaymentDatabaseMockRecorder) MarkFailed(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockPaymentDatabase)(nil).MarkFailed), orderID)
}

// SaveFailedPublishEvent mocks base method.
func (m *MockPaymentDatabase) SaveFailedPublishEvent(ctx context.Context, param *models.FailedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFailedPublishEvent", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFailedPublishEvent indicates an expected call of SaveFailedPublishEvent.
func (mr *MockPaymentDatabaseMockRecorder) SaveFailedPublishEvent(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFailedPublishEvent", reflect.TypeOf((*MockPaymentDatabase)(nil).SaveFailedPublishEvent), ctx, param)
}

// SavePayment mocks base method.
func (m *MockPaymentDatabase) SavePayment(ctx context.Context, param *models.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePayment", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePayment indicates an expected call of SavePayment.
func (mr *MockPaymentDatabaseMockRecorder) SavePayment(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePayment", reflect.TypeOf((*MockPaymentDatabase)(nil).SavePayment), ctx, param)
}

// SavePaymentAnomaly mocks base method.
func (m *MockPaymentDatabase) SavePaymentAnomaly(ctx context.Context, param *models.PaymentAnomaly) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePaymentAnomaly", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePaymentAnomaly indicates an expected call of SavePaymentAnomaly.
func (mr *MockPaymentDatabaseMockRecorder) SavePaymentAnomaly(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePaymentAnomaly", reflect.TypeOf((*MockPaymentDatabase)(nil).SavePaymentAnomaly), ctx, param)
}

// SavePaymentRequest mocks base method.
func (m *MockPaymentDatabase) SavePaymentRequest(ctx context.Context, param *models.PaymentRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePaymentRequest", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePaymentRequest indicates an expected call of SavePaymentRequest.
func (mr *MockPaymentDatabaseMockRecorder) SavePaymentRequest(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePaymentRequest", reflect.TypeOf((*MockPaymentDatabase)(nil).SavePaymentRequest), ctx, param)
}

// UpdateFailedPaymentRequest mocks base method.
func (m *MockPaymentDatabase) UpdateFailedPaymentRequest(ctx context.Context, paymentRequestID int64, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFailedPaymentRequest", ctx, paymentRequestID, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFailedPaymentRequest indicates an expected call of UpdateFailedPaymentRequest.
func (mr *MockPaymentDatabaseMockRecorder) UpdateFailedPaymentRequest(ctx, paymentRequestID, notes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFailedPaymentRequest", reflect.TypeOf((*MockPaymentDatabase)(nil).UpdateFailedPaymentRequest), ctx, paymentRequestID, notes)
}

// UpdatePendingPaymentRequest mocks base method.
func (m *MockPaymentDatabase) UpdatePendingPaymentRequest(ctx context.Context, paymentRequestID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePendingPaymentRequest", ctx, paymentRequestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePendingPaymentRequest indicates an expected call of UpdatePendingPaymentRequest.
func (mr *MockPaymentDatabaseMockRecorder) UpdatePendingPaymentRequest(ctx, paymentRequestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePendingPaymentRequest", reflect.TypeOf((*MockPaymentDatabase)(nil).UpdatePendingPaymentRequest), ctx, paymentRequestID)
}

// UpdateSuccessPaymentRequest mocks base method.
func (m *MockPaymentDatabase) UpdateSuccessPaymentRequest(ctx context.Context, paymentRequestID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSuccessPaymentRequest", ctx, paymentRequestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSuccessPaymentRequest indicates an expected call of UpdateSuccessPaymentRequest.
func (mr *MockPaymentDatabaseMockRecorder) UpdateSuccessPaymentRequest(ctx, paymentRequestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSuccessPaymentRequest", reflect.TypeOf((*MockPaymentDatabase)(nil).UpdateSuccessPaymentRequest), ctx, paymentRequestID)
}

// MockXenditClient is a mock of XenditClient interface.
type MockXenditClient struct {
	ctrl     *gomock.Controller
	recorder *MockXenditClientMockRecorder
}

// MockXenditClientMockRecorder is the mock recorder for MockXenditClient.
type MockXenditClientMockRecorder struct {
	mock *MockXenditClient
}

// NewMockXenditClient creates a new mock instance.
func NewMockXenditClient(ctrl *gomock.Controller) *MockXenditClient {
	mock := &MockXenditClient{ctrl: ctrl}
	mock.recorder = &MockXenditClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXenditClient) EXPECT() *MockXenditClientMockRecorder {
	return m.recorder
}

// CheckInvoiceStatus mocks base method.
func (m *MockXenditClient) CheckInvoiceStatus(ctx context.Context, externalID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInvoiceStatus", ctx, externalID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInvoiceStatus indicates an expected call of CheckInvoiceStatus.
func (mr *MockXenditClientMockRecorder) CheckInvoiceStatus(ctx, externalID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInvoiceStatus", reflect.TypeOf((*MockXenditClient)(nil).CheckInvoiceStatus), ctx, externalID)
}

// CreateInvoice mocks base method.
func (m *MockXenditClient) CreateInvoice(ctx context.Context, request models.XenditInvoiceRequest) (*models.XenditInvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", ctx, request)
	ret0, _ := ret[0].(*models.XenditInvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockXenditClientMockRecorder) CreateInvoice(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockXenditClient)(nil).CreateInvoice), ctx, request)
}

// MockPaymentEventPublisher is a mock of PaymentEventPublisher interface.
type MockPaymentEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentEventPublisherMockRecorder
}

// MockPaymentEventPublisherMockRecorder is the mock recorder for MockPaymentEventPublisher.
type MockPaymentEventPublisherMockRecorder struct {
	mock *MockPaymentEventPublisher
}

// NewMockPaymentEventPublisher creates a new mock instance.
func NewMockPaymentEventPublisher(ctrl *gomock.Controller) *MockPaymentEventPublisher {
	mock := &MockPaymentEventPublisher{ctrl: ctrl}
	mock.recorder = &MockPaymentEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentEventPublisher) EXPECT() *MockPaymentEventPublisherMockRecorder {
	return m.recorder
}

// PublishPaymentStatus mocks base method.
func (m *MockPaymentEventPublisher) PublishPaymentStatus(ctx context.Context, orderID int64, status string, topic string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPaymentStatus", ctx, orderID, status, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPaymentStatus indicates an expected call of PublishPaymentStatus.
func (mr *MockPaymentEventPublisherMockRecorder) PublishPaymentStatus(ctx, orderID, status, topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPaymentStatus", reflect.TypeOf((*MockPaymentEventPublisher)(nil).PublishPaymentStatus), ctx, orderID, status, topic)
}

// MockAuditLogRepository is a mock of AuditLogRepository interface.
type MockAuditLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRepositoryMockRecorder
}

// MockAuditLogRepositoryMockRecorder is the mock recorder for MockAuditLogRepository.
type MockAuditLogRepositoryMockRecorder struct {
	mock *MockAuditLogRepository
}

// NewMockAuditLogRepository creates a new mock instance.
func NewMockAuditLogRepository(ctrl *gomock.Controller) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{ctrl: ctrl}
	mock.recorder = &MockAuditLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRepository) EXPECT() *MockAuditLogRepositoryMockRecorder {
	return m.recorder
}

// SaveAuditLog mocks base method.
func (m *MockAuditLogRepository) SaveAuditLog(ctx context.Context, entry *models.PaymentAuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAuditLog", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAuditLog indicates an expected call of SaveAuditLog.
func (mr *MockAuditLogRepositoryMockRecorder) SaveAuditLog(ctx, entry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAuditLog", reflect.TypeOf((*MockAuditLogRepository)(nil).SaveAuditLog), ctx, entry)
}

// ListAuditLogs mocks base method.
func (m *MockAuditLogRepository) ListAuditLogs(ctx context.Context, filter models.AuditLogFilter) (models.AuditLogPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditLogs", ctx, filter)
	ret0, _ := ret[0].(models.AuditLogPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditLogs indicates an expected call of ListAuditLogs.
func (mr *MockAuditLogRepositoryMockRecorder) ListAuditLogs(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditLogs", reflect.TypeOf((*MockAuditLogRepository)(nil).ListAuditLogs), ctx, filter)
}

// GetDailyReport mocks base method.
func (m *MockAuditLogRepository) GetDailyReport(ctx context.Context, from, to time.Time) ([]models.AuditDailyReportItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyReport", ctx, from, to)
	ret0, _ := ret[0].([]models.AuditDailyReportItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyReport indicates an expected call of GetDailyReport.
func (mr *MockAuditLogRepositoryMockRecorder) GetDailyReport(ctx, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyReport", reflect.TypeOf((*MockAuditLogRepository)(nil).GetDailyReport), ctx, from, to)
}

// WatchInsertStream mocks base method.
func (m *MockAuditLogRepository) WatchInsertStream(ctx context.Context, out chan<- models.PaymentAuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchInsertStream", ctx, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// WatchInsertStream indicates an expected call of WatchInsertStream.
func (mr *MockAuditLogRepositoryMockRecorder) WatchInsertStream(ctx, out interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchInsertStream", reflect.TypeOf((*MockAuditLogRepository)(nil).WatchInsertStream), ctx, out)
}
